### ISSUE TITLE
Main todo list to stable release

### ISSUE THREAD

**Issue by mttbernardini** [mebeim/jsquiz#3]
Here's a todo list of the things we have to fix/rework in order to arrive to a stable and decent release:

**Misc**
- [ ] Remove JQuery
  - [ ] Create selector function
  - [x] Implement `addClass()` and `removeClass()`
  - [ ] Implement `each()` method
  - [ ] Replace event bindings with appropriate `addEventListener` (or make a custom method to support `attachEvent` for IE)
- [ ] Make all transitions using CSS and few classes (see `animateIn()`, `animateOut()`, `animateLevelUp()`)
- [ ] Is there a way to better implement the *onpress* event?

**Bugs**
- [ ] Make snippet area scrollable on mobile (for long snippets)
- [ ] Add &lt;noscript&gt; section

**Features**
- [ ] Add an *exit* button during game

**Comment by mttbernardini** [comment]
**Question:** should we even support IE < 9 in the first place? I personally think no.
So at this point supporting `attachEvent()` would be unnecessary, as IE9 supports the standard one.
